name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install required packages 
      run: npm install  
    - name: Build dist nodejs 
      run: npm run build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag todoapp:$(date +%s)

    - name: Docker Publish
      # You may pin to the exact commit or the version.
      # uses: manusa/actions-publish-docker@db938e45d2a3487e0eab9646e83550f554c17af3
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        # Name of the Docker image
        name: todoapp
        # Tag for the Docker image
        tag: "0.1.1"
        # Script body to compute tag name for the Docker image, has context as the main function argument
        tag script: # optional
        # Username for Docker registry
        username: charlescr
        # Password for Docker registry
        password: ${{ secrets.ACR_PWD }}
        # Registry URL
        registry: charlescr.azurecr.io
        # Don't skip pull requests
        include pull requests: # optional
        # Path to Dockerfile
        dockerfile path: # optional
